export { ReactComponent as Pen } from './pen.svg'
export { ReactComponent as Arrow } from './arrow.svg'
export { ReactComponent as Hand } from './hand.svg'
export { ReactComponent as Union } from './union.svg'
export { ReactComponent as Subtract } from './subtract.svg'
export { ReactComponent as Intersect } from './intersect.svg'
export { ReactComponent as Exclude } from './exclude.svg'
