# fly.toml app configuration file generated for socket-y
# https://fly.io/apps/socket-y/monitoring
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'socket-y'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
